### PR TITLE
update :: number input && output view

### PR DESCRIPTION
**Pull request by erdemuslu**

### CODE REVIEW

**Comment by ashikvarma11** [comment]
@erdemuslu I checked it. The circles are bigger now. Its taking a lot of space I guess. I think, it would be better to have the old size for the circles. How would it look like if we resize the text inside of the circle? I mean, reduce font size  proportionally if the value is greater than 3 digits.

**Comment by erdemuslu** [comment]
@ashikvarma11 I updated. Can you check it?

**Comment by erdemuslu** [comment]
@ashikvarma11 Can you check and merge it if it's ok? Thanks.

**Comment by ashikvarma11** [comment]
@erdemuslu  I see that the branch has conflicts. Have you merged your branch with latest code? 

Steps

1. checkout master.
2. git pull origin master
3. checkout your branch
4. git merge master
5. git push fork <your branch name>

**Comment by erdemuslu** [comment]
@ashikvarma11 I updated.

**Comment by ashikvarma11** [comment]
@erdemuslu  I'll review the code

**Comment by ashikvarma11** [comment]
@erdemuslu  Thanks for the contribution 👍 💯

**Pull request merged**
